# robot_base_frame: base_footprint #base_footprint
# resolution: 0.01
# footprint: [[0.515, 0.265], [-0.515, 0.265], [-0.515, -0.265], [0.515, -0.265]]
# footprint_padding: 0.01
# # obstacle_range: 2.5
# # raytrace_range: 3.0
# update_frequency: 5.0
# publish_frequency: 2.0
# transform_tolerance: 0.5
# resolution: 0.1
# always_send_full_costmap: true

# #layer definitions
# static_layer:
#     map_topic: /map
#     # track_unknown_space: false
#     map_subscribe_transient_local: true
#     subscribe_to_updates: true

# obstacle_layer:
#     observation_sources: laser
#     laser: {sensor_frame: laser  , data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

# inflation_g:
#     inflation_radius: 0.3 #*
#     # cost_scaling_factor: 10.0 #*

     
# inflation_l:
#     inflation_radius: 0.3 #*
#     # cost_scaling_factor: 10.0 #*


# cost_scaling_l:
#     cost_scaling_factor: 10.0 #*

# cost_scaling_g:
#     cost_scaling_factor: 10.0 #*

# footprint: [[-0.12, -0.12], [-0.12, 0.12], [0.12, 0.12], [0.12, -0.12]]
footprint: [[0.500, 0.200], [-0.500, 0.200], [-0.500, -0.200], [0.500, -0.200]] #0.265 #0.515
footprint_padding: 0.01

robot_base_frame: base_footprint

map_update_rate: 5 #20
# transform_tolerance: 0.5

# resolution: 0.3r

# obstacle_range: 5.5
# raytrace_range: 6.0

obstacle_range: 2.5
raytrace_range: 3.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, expected_update_rate: 0.5}

inflation_g:
    inflation_radius: 0.05
    
inflation_l:
    inflation_radius: 0.05

cost_scaling_l:
    cost_scaling_factor: 0.01 #*

cost_scaling_g:
    cost_scaling_factor: 0.01 #*