# global_costmap:
#   global_frame: map
#   rolling_window: false
#   track_unknown_space: true
#   static_map: true
#   plugins:
#     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
#     - {name: inflation_g,         type: "costmap_2d::InflationLayer"}
#     - {name: cost_scaling_g,     type: "costmap_2d::InflationLayer"}

global_frame: map
rolling_window: false
track_unknown_space: true
resolution: 0.2
update_frequency: 3.0
transform_tolerance: 0.5 #0.5

# publish_frequency: 6.0
plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation_g,               type: "costmap_2d::InflationLayer"}
  - {name: cost_scaling_g,     type: "costmap_2d::InflationLayer"}
