waypoints:
  - point:
      x: -7.88      #2.6 
      y:  -7.95         #3.4
      th: -120           #-25.2 # in degree 40x2
  - point:
      x: -7.88            #2.6
      y:  -7.95           # 3.4
      th: 51            #136 # in degree    
  - point:
      x: -2.1           #-1.5
      y: 0.1            #8.8
      th: 51          #136 # in degree 
  - point:
      x: -2.1 #-1.5
      y: 0.1 #8.8
      th: -120 #-136 # in degree 
  - point:
      x: -7.88                 #-1.68
      y:  -7.95                 #7.4
      th: -120                #-136 # in degree #0.005410243500890815
#   - point:
#       x: 4.217953681945801
#       y: 0.38314366340637207
#       th: 0 # in degree 
  - point:
      x: -7.88 #-1.68
      y: -7.95 #7.4
      th: 51 #-50 # in degree 
  - point:
      x: -2.1           #-1.5
      y: 0.1            #8.8
      th: 51          #136 # in degree
#   - point:
#       x: 4.217953681945801
#       y: 0.38314366340637207
#       th: 0 # in degree 
  - point:
      x: -2.1 #-1.5
      y: 0.1 #8.8
      th: -120 #-136 # in degree 

